DROP TABLE IF EXISTS supplier CASCADE;
DROP TABLE IF EXISTS product_type CASCADE;
DROP TABLE IF EXISTS product_list CASCADE;

DROP SEQUENCE IF EXISTS supplier_seq;
DROP SEQUENCE IF EXISTS product_type_seq;
DROP SEQUENCE IF EXISTS product_list_seq;