server:
  port: 8081
  servlet:
    context-path: /

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/warehouse?currentSchema=inventory_control
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource

    hikari:
      maximum-pool-size: 10
      connection-timeout: 120000
      max-lifetime: 120000
      minimum-idle: 4

  liquibase:
    enabled: false
    change-log: db/master.xml

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mybatis/mapper/*.xml

logging:
  level:
    com.spring.ibatis: DEBUG